# Generated by Django 4.2.4 on 2023-08-23 10:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
